/**
 * app/api/approvals/[id]/photos/[asset_id]/route.ts
 * GET /api/approvals/:id/photos/:asset_id?sig=&exp=
 * Validates HMAC-signed URL, then streams photo from Supabase Storage.
 * I2: signed URL generated by generatePhotoSignedUrl() in spine.ts.
 * Payload: {approval_id}:{asset_id}:{exp}
 */

import { NextRequest } from 'next/server'
import { createHmac, timingSafeEqual } from 'crypto'
import { createAdminClient } from '@/lib/supabase/admin'

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string; asset_id: string } }
): Promise<Response> {
  const url = new URL(req.url)
  const sig = url.searchParams.get('sig') ?? ''
  const expStr = url.searchParams.get('exp') ?? '0'
  const exp = parseInt(expStr, 10)

  if (!sig || !exp) return new Response('missing sig or exp', { status: 400 })
  if (Date.now() / 1000 > exp) return new Response('link expired', { status: 410 })

  const secret = process.env.APPROVAL_PHOTO_HMAC_SECRET
  if (!secret) return new Response('server misconfigured', { status: 500 })

  // Validate HMAC: payload = {approval_id}:{asset_id}:{exp}
  const expected = createHmac('sha256', secret)
    .update(`${params.id}:${params.asset_id}:${exp}`)
    .digest('hex')

  let sigBuf: Buffer, expBuf: Buffer
  try {
    sigBuf = Buffer.from(sig, 'hex')
    expBuf = Buffer.from(expected, 'hex')
  } catch {
    return new Response('invalid sig format', { status: 400 })
  }

  if (sigBuf.length !== expBuf.length || !timingSafeEqual(sigBuf, expBuf)) {
    return new Response('invalid signature', { status: 403 })
  }

  // Look up asset path from approval_request.action_payload.assets
  const supabase = createAdminClient()
  const { data: ar } = await supabase
    .from('approval_requests')
    .select('action_payload')
    .eq('id', params.id)
    .single()

  const assets = ((ar?.action_payload as any)?.assets ?? []) as Array<{
    id: string
    bucket: string
    path: string
    mime?: string
  }>
  const asset = assets.find((a) => a.id === params.asset_id)
  if (!asset) return new Response('asset not found', { status: 404 })

  const { data: blob } = await supabase.storage.from(asset.bucket).download(asset.path)
  if (!blob) return new Response('storage error', { status: 502 })

  return new Response(blob.stream(), {
    headers: {
      'Content-Type': asset.mime ?? 'image/jpeg',
      'Cache-Control': 'private, max-age=1800',
    },
  })
}
